### ISSUE TITLE
Sometimes DiagramComponent fail to create a node from Palette or saved JSON

### ISSUE THREAD

**Issue by yamadamasaki** [syncfusion/ej2-javascript-ui-controls#103]
JSON output of a diagram may contain a null-valued annotation content.

But `controls/diagrams/src/diagram/utility/dom-util.ts#wordWrapping()` assumes non-null `content` variable, so String.split() may fail.

`let content: string = textValue || text.content;` should be `let content: string = textValue || text.content || "";` or some other workaround.

**Comment by gowtham-syncfusion** [comment]
Hi @yamadamasaki, 
 
On the further analysis of the shared details, to avoid the reported issue, we suggest you add the null check validation and set empty(“”) in case the content value is null using getNodeDefaults because the content property of the annotation is not nullable. 
  
Sample link: https://stackblitz.com/edit/e81efo-1mmhpt?file=index.js 
 
Regards,    
Gowtham
