### ISSUE TITLE
Pivotview throws an error when using excluded and calculated fields

### ISSUE THREAD

**Issue by xy235** [syncfusion/ej2-javascript-ui-controls#112]
Hi,
we have been using pivotview in our hospital information system project for over a year. We have recently upgraded to the latest version and discovered a bug when using both excluded and calculated fields in the component. 

The bug can be observed in the following stackblitz project:
https://stackblitz.com/edit/syncfusion-pivotview-excluded-fields-bug

After opening the pivotFieldList and deselecting any field other than "count", the component throws an error in the console.  After investigation we have found out that the component incorrectly removes the field definition for the calculated field 'count' and is therefore unable to access it.

We have already created a pull request that fixes this problem, which can be found below:
https://github.com/syncfusion/ej2-javascript-ui-controls/pull/111

We hope you'll be able to quickly investigate and close this issue with all the provided information.

**Comment by maniram21** [comment]
Hi Customer,  
   
We are glad to inform you that the fix for the issue “Getting script error while excluding any fields in report” has been included in the weekly release (v19.1.0.65).  
   
We thank you for your support and appreciate your patience in waiting for this release. Please contact us if you would require any further assistance.  
   
Regards,  
Manikandan
