### ISSUE TITLE
Gantt Collapse/Expand at level is not working with enableVirtualization

### ISSUE THREAD

**Issue by Ihor93** [syncfusion/ej2-javascript-ui-controls#117]
Trying to implement custom toolbar element "expand at level" but function "expandAtLevel " working only with virtual scroll disabled. Is there are workaround to solve this? 

See stack trace.
TypeError: Cannot read property 'querySelectorAll' of undefined
    at GanttChart.expandCollapseChartRows (gantt-chart.js:725)
    at GanttChart.expandedGanttRow (gantt-chart.js:686)
    at GanttTreeGrid.expanded (tree-grid.js:234)
    at Observer.notify (observer.js:99)
    at TreeGrid.Base.trigger (base.js:181)
    at Observer.<anonymous> (treegrid.js:2321)
    at Observer.notify (observer.js:102)
    at TreeGrid.Base.trigger (base.js:181)
    at TreeGrid.expandRow (treegrid.js:2314)
    at TreeGrid.expandAtLevel (treegrid.js:2386)
    at GanttChart.expandAtLevel (gantt-chart.js:786)
    at GanttComponent.Gantt.expandAtLevel (gantt.js:2042)
    
    **Thanks in advance for any solution.**

**Comment by MonishaSivanthilingam** [comment]
Hi Ihor93,

Greetings from Syncfusion support.

We were able to replicate the issue you reported. We will analyze it and provide you with further updates within two business days(July 15, 2021).

We appreciate your patience until then.

Regards,
Monisha.

**Comment by MonishaSivanthilingam** [comment]
Hi Ihor93,

We apologize for the inconvenience caused.

The reported issue “[Gantt Collapse/Expand at level method is not working with enableVirtualization](https://www.syncfusion.com/feedback/27047/gantt-collapse-expand-at-level-method-is-not-working-with-enablevirtualization)” has been fixed internally. However, we are still ensuring a few dependent use cases. Hence, the fix was not included in this patch release. We will provide the fix for the issue in the 2021 Volume 2 SP release scheduled for the mid of August 2021.

We appreciate your patience until then.

Regards,
Monisha.

**Comment by MonishaSivanthilingam** [comment]
Hi Ihor93,


We apologize for the inconvenience caused.


The reported issue “[Gantt Collapse/Expand at level method is not working with enableVirtualization](https://www.syncfusion.com/feedback/27047/gantt-collapse-expand-at-level-method-is-not-working-with-enablevirtualization)” has been fixed internally. However, due to a few technical issues, the fix was not included in this patch release. We will definitely include the fix in the next patch release scheduled for August 18, 2021.


Once again, we apologize for the inconvenience caused.


Regards,

Monisha.

**Comment by poojapriya-krishnamoorthy** [comment]
Hi Ihor93,

Thanks for your patience.

The issue reported in “[Issue in Expand/Collapse at level](https://www.syncfusion.com/feedback/27047/gantt-collapse-expand-at-level-method-is-not-working-with-enablevirtualization)” has been fixed in version 19.2.56. Please find the release notes from below link.
https://ej2.syncfusion.com/react/documentation/release-notes/19.2.56/?type=all#gantt

Please contact us if you require further assistance on this.

Regards,
Pooja K.
