### ISSUE TITLE
PdfViewer: Disabling the form-field editor via toolbar items causes an exception when interacting with form fields

### ISSUE THREAD

**Issue by SergenN** [syncfusion/ej2-javascript-ui-controls#144]
when you disable the annotation editor using the following settings: 

`
    <ejs-pdfviewer
      [toolbarSettings]="toolbarSettings"
      [contextMenuOption]="'None'"
      [enableBookmark]="false"
      [enableTextMarkupAnnotation]="false"
      [serviceUrl]="service">
    </ejs-pdfviewer>`

`  toolbarSettings: ToolbarSettingsModel = {
    toolbarItems: [
      'OpenOption',
      'PageNavigationTool',
      'MagnificationTool',
      'PanTool',
      'SelectionTool',
      'SearchOption',
      'PrintOption',
      'DownloadOption',
      'UndoRedoTool'
    ]
  };`

Clicking an form-field works fine the first time but after the second time the following exception occurs:

`TypeError: undefined is not an object (evaluating 'this.annotationModule.textMarkupAnnotationModule.selectTextMarkupCurrentPage')` 

Which appears to be happening [here](https://github.com/syncfusion/ej2-javascript-ui-controls/blob/bb61c5361a88c6bcbb8cc8d115f86f126622db1a/controls/pdfviewer/src/pdfviewer/pdfviewer.ts#L7813). This exception blocks the signature dialog to open when it has been closed for the first time.

Hovering over the buttons in the toolbar will result in the following exception:
`TypeError: undefined is not an object (evaluating 'this.annotationToolbarModule.shapeToolbarElement.contains')`
Which appears to be originating from [here](https://github.com/syncfusion/ej2-javascript-ui-controls/blob/bb61c5361a88c6bcbb8cc8d115f86f126622db1a/controls/pdfviewer/src/pdfviewer/toolbar/toolbar.ts#L1214).

**Comment by ShaminiKiruba** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/SHAMIN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/SHAMIN~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/SHAMIN~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal>Hi,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



Query | Response
-- | --
when   you disable the annotation editor using the following settings:   <ejs-pdfviewer   [toolbarSettings]="toolbarSettings"   [contextMenuOption]="'None'" [enableBookmark]="false"   [enableTextMarkupAnnotation]="false" [serviceUrl]="service">   </ejs-pdfviewer>   toolbarSettings: ToolbarSettingsModel = { toolbarItems: [   'OpenOption', 'PageNavigationTool', 'MagnificationTool', 'PanTool',   'SelectionTool', 'SearchOption', 'PrintOption', 'DownloadOption',   'UndoRedoTool' ] };   Clicking   an form-field works fine the first time but after the second time the   following exception occurs:   TypeError: undefined is not an object (evaluating   'this.annotationModule.textMarkupAnnotationModule.selectTextMarkupCurrentPage')   Which   appears to be happening here. This   exception blocks the signature dialog to open when it has been closed for the   first time. | We were able to reproduce the below script error with the   given details. Kindly confirm if this is the issue you are reporting.       https://www.syncfusion.com/downloads/support/directtrac/general/ze/console_error1198686873       Below is the sample we used at our end to replicate the   issue.       Sample: https://stackblitz.com/edit/angular-wf5rwu?file=app.component.ts       Kindly share the modified sample and clear steps to   replicate the issue if you are facing a different issue
Hovering over the buttons in the toolbar will result in the following exception:   TypeError: undefined is not an object (evaluating   'this.annotationToolbarModule.shapeToolbarElement.contains')   Which appears to be originating from here. | We were unable to replicate this issue with the below   (same) sample.       Sample: https://stackblitz.com/edit/angular-wf5rwu?file=app.component.ts       Kindly share the modified sample and the replication video to reproduce the issue at our end so that we can provide a solution at the earliest.



<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Regards,<o:p></o:p></p>

<p class=MsoNormal>Shamini<o:p></o:p></p>


</body>

</html>

**Comment by SergenN** [comment]
Hi Shamini,

The first error is correct. 
The second error can be produced using the following notation: 
```toolbarSettings: any = { toolbarItems: [...]}``` 

https://stackblitz.com/edit/angular-wf5rwu-fdlh4s?file=app.component.ts

Thank you for looking into it!

**Comment by ShaminiKiruba** [comment]
Hi SergenN,

Thanks for sharing the sample that reproduces the issue. We will validate both the issues and update further details in two business days on **February 28, 2022**.

Regards,
Shamini

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/33061/script-error-is-thrown-on-clicking-the-form-field-for-the-second-time

**Comment by SergenN** [comment]
Hi, i can't follow these issues they appear to be private?

**Comment by ShaminiKiruba** [comment]
Hi Sergen,

Sorry for the inconvenience. We have now made the feedback visible to you.

Regards,
Shamini
