### ISSUE TITLE
rich-text-editor and images

### ISSUE THREAD

**Issue by vegarringdal** [syncfusion/ej2-javascript-ui-controls#52]
rich-text-editor and images

Im trying to figure out the best way to save content and load same content later.
Would be nice to hear how you use it, with images..

**Comment by PrinceOliver** [comment]
Hi @vegarringdal ,

Thank you for contacting us.

You can get the RichTextEditor’s content using the following method and property.

•	**getHtml** – this method returns the HTML content from RTE
https://ej2.syncfusion.com/javascript/documentation/api/rich-text-editor/#gethtml
•	**value** – this property returns the value of the RTE control as HTML string
https://ej2.syncfusion.com/javascript/documentation/api/rich-text-editor/#value

Using the above API you can get the RTE’s content and save it. To load the saved content into RTE control, you can use the **value** property and set the HTML string from the saved location into the control. Since the content is HTML formatted string, the images can be saved and loaded in the control later.

Let us know if you need any further assistance on this.

Regards,
Prince

**Comment by rajendranr-5483** [comment]
Hi @vegarringdal ,

We are closing this thread since we didn't hear any update from you. Please reopen this thread if you have any other concerns about this requirement.
