### ISSUE TITLE
TextBox value change problem

### ISSUE THREAD

**Issue by ismail-codar** [syncfusion/ej2-javascript-ui-controls#65]
Please look at this section:
https://github.com/syncfusion/ej2-javascript-ui-controls/blob/master/controls/inputs/src/textbox/textbox.ts#L250

newProp.value is not effects to value change. It can be like this:
```js
if (!this.isBlank(newProp.value)) {
    this.value = newProp.value.toString();
}
```

**Comment by sureshkumar1115** [comment]
Hi @ismail-codar ,

We have validated your suggestion. we would like to say this in our source **this.value** updated automatically from our core logic. So, no need to mention here with **newProp.value** instead of **this.value**. the logic of your mentioned code block **converts your entered value to string type to update the textbox component**.

Regards,
Sureshkumar P

**Comment by ismail-codar** [comment]
In one day.. I'll send a codesanbox demo that simulates the problem.

**Comment by ismail-codar** [comment]
Sorry. I cannot reproduce. But if I encounter the same problem, I will reopen it.
