### ISSUE TITLE
Rich text editor content preview

### ISSUE THREAD

**Issue by THoVer** [syncfusion/ej2-javascript-ui-controls#72]
Hello,

I struggle to render html content outside of rich-text-editor with exactly the same appearance as it would render inside of editor. 
Some of styles in editor are applied from css stylesheets, and are not applied to html element inline style. 

Example in [demo](https://ej2.syncfusion.com/javascript/demos/#/material/rich-text-editor/blog-posting.html) - try to add new comment with H1, H2, H3, H4 elements. After submiting form - styles are lost and headings fallback to default browser appearance.

I would expect that `editor.getHtml()` would return all the markup required for rendering rte content outside of editor.

Is there a way to achieve this?

**Comment by Indrajith-Sync** [comment]
Hi Thover,

Greetings from Syncfusion support,

We have already considered “**Return the HTML with related content styles**“ as a bug from our end and logged the report for the same and the fix will be included with our 2020 Volume 1 Main release.

You can now track the current status of the report, review the proposed resolution timeline, and contact us for any further inquiries through this link: 

https://www.syncfusion.com/feedback/12848/

Regards,
Indrajith

**Comment by Indrajith-Sync** [comment]
Hi Thover, 
 
Thanks for your patience, 
 
We have resolved the issue “**Maintaining RichTextEditor content styles while using it in other places**” and the fix is now available with the package version **18.1.53**. So we suggest you to refer the below documentation for reference. 
 
Documentation: https://ej2.syncfusion.com/documentation/rich-text-editor/styling/#editor-content-styles 
 
Regards, 
Indrajith

**Comment by rajendranr-5483** [comment]
@THoVer ,

We are closing this thread now. Since we are able to achieve your requirement using styles refer from the application end. Please reopen this thread if you have any other concerns or requirements.
